
services:
  web:
    image: igorchinyakov/pet-family-backend:1.0
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - postgres
      - seq
      - minio
      - rabbitmq
  seq:
    container_name: seq
    image: datalust/seq:latest
    restart: always
    environment: 
        - ACCEPT_EULA=Y
    ports:
        - 5341:5341
        - 8081:80
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: pet_family
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
    ports:
    - 5434:5432
    volumes:
    - postgres-data:/var/lib/postgresql/data
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    restart: always
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
  nginx:
    image: nginx:latest
    ports: 
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
    postgres-data:
    minio_data:
    rabbitmq_data: