
services:
  seq:
    container_name: seq
    image: datalust/seq:latest
    restart: always
    environment: 
        - ACCEPT_EULA=Y
    ports:
        - 5341:5341
        - 8081:80
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: pet_family
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
    ports:
    - 5434:5432
    volumes:
    - postgres-data:/var/lib/postgresql/data
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    restart: always


volumes:
    postgres-data:
    minio_data:
    
